// Normalizes the Volt Academy design system export (.claude/design-system/tokens.json)
// into src/tokens/tokens.json, the shape the Tailwind preset and TS code consume.
// Usage: node scripts/generate-tokens.mjs [--check]
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(packageRoot, "../../.claude/design-system/tokens.json");
const outputPath = resolve(packageRoot, "src/tokens/tokens.json");

// Expo Google Fonts registers each weight as its own family, e.g. Inter_600SemiBold.
const WEIGHT_NAMES = {
  100: "Thin",
  200: "ExtraLight",
  300: "Light",
  400: "Regular",
  500: "Medium",
  600: "SemiBold",
  700: "Bold",
  800: "ExtraBold",
  900: "Black",
};

const px = (value) => Number.parseFloat(value);

const hexToChannels = (hex) => {
  const value = hex.replace("#", "");
  return [0, 2, 4].map((i) => Number.parseInt(value.slice(i, i + 2), 16)).join(" ");
};

const stripPrefix = (name, prefix) => name.replace(new RegExp(`^${prefix}-`), "");

const source = JSON.parse(readFileSync(sourcePath, "utf8"));
const schemes = source.color.themes.map((theme) => theme.id);

const byScheme = (tokens, transform = (v) => v, rename = (n) => n) =>
  Object.fromEntries(
    schemes.map((scheme) => [
      scheme,
      Object.fromEntries(tokens.map((t) => [rename(t.name), transform(t.value[scheme])])),
    ]),
  );

const fontFamilies = source.type.families;

const typography = Object.fromEntries(
  source.type.groups.flatMap((group) =>
    group.styles.map((style) => {
      const primaryFamily = fontFamilies[group.family].match(/"([^"]+)"/)[1];
      return [
        style.name,
        {
          family: group.family,
          fontSize: px(style.fontSize),
          lineHeight: px(style.lineHeight),
          fontWeight: style.fontWeight,
          letterSpacing: style.letterSpacing ? px(style.letterSpacing) : 0,
          uppercase: style.name === "eyebrow",
          nativeFontFamily: `${primaryFamily.replace(/\s+/g, "")}_${style.fontWeight}${WEIGHT_NAMES[style.fontWeight]}`,
        },
      ];
    }),
  ),
);

const tokens = {
  $comment: "Generated by scripts/generate-tokens.mjs from .claude/design-system/tokens.json. Do not edit.",
  name: source.name,
  schemes,
  colors: byScheme(source.color.tokens),
  colorChannels: byScheme(source.color.tokens, hexToChannels),
  fontFamilies,
  typography,
  spacing: Object.fromEntries(source.spacing.tokens.map((t) => [stripPrefix(t.name, "space"), px(t.value)])),
  radius: Object.fromEntries(source.radius.tokens.map((t) => [stripPrefix(t.name, "radius"), px(t.value)])),
  shadow: byScheme(source.shadow.tokens, undefined, (n) => stripPrefix(n, "shadow")),
};

const output = `${JSON.stringify(tokens, null, 2)}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(outputPath, "utf8");
  } catch {}
  if (current !== output) {
    console.error("src/tokens/tokens.json is out of date with .claude/design-system/tokens.json.");
    console.error("Run: pnpm --filter @electrical-hero/design-system tokens");
    process.exit(1);
  }
  console.log("Design tokens are up to date.");
} else {
  writeFileSync(outputPath, output);
  console.log(`Wrote ${outputPath}`);
}
